# generated by fastapi-codegen:
#   filename:  FF_API.yaml
#   timestamp: 2024-11-22T13:36:24+00:00

from __future__ import annotations

import datetime
from typing import List, Type

from fastapi import APIRouter, Depends, HTTPException, Query, Path

import uuid
from app.models import Reservation as PydanticReservation
from app.models_sqlalchemy import Reservation as SQLAlchemyReservation
from datetime import date
from ..dependencies import *
from app.routers.auth import get_current_user


router = APIRouter(
    tags=['Reservations'],
    dependencies=[Depends(get_current_user)]
)

@router.get(
    '/v1/reservations',
    response_model=List[PydanticReservation],
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['Reservations'],
)
def get_reservations(db: Session = Depends(get_db)) -> list[Type[PydanticReservation]]:
    """
    Get the list of reservations
    """
    return db.query(SQLAlchemyReservation).all()


@router.post(
    '/v1/reservations',
    response_model=PydanticReservation,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '422': {'model': Error},
        '500': {'model': Error},
    },
    tags=['Reservations'],
)
def create_reservation(reservation: PydanticReservation, db: Session = Depends(get_db)):
    """
    Create a new reservation
    """
    if not reservation.id:
        reservation.id = str(uuid.uuid4())

    new_reservation = SQLAlchemyReservation(
        id=reservation.id,
        tripId=reservation.trip.id if reservation.trip else None,
        date=reservation.date or datetime.UTC,
        reservedSeats=reservation.reservedSeats,
        totalPrice=reservation.totalPrice,
        userId=reservation.userId,
    )
    db.add(new_reservation)
    db.commit()
    db.refresh(new_reservation)
    return new_reservation


@router.get(
    '/v1/reservations/{reservation_id}',
    response_model=PydanticReservation,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['Reservations'],
)
def get_reservation(reservation_id: str, db: Session = Depends(get_db)):
    """
    Get a reservation by ID
    """
    reservation = db.query(SQLAlchemyReservation).filter(SQLAlchemyReservation.id == reservation_id).first()
    if not reservation:
        raise HTTPException(status_code=404, detail="Reservation not found")
    return reservation


@router.put(
    '/v1/reservations/{reservation_id}',
    response_model=PydanticReservation,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['Reservations'],
)
def update_reservation(reservation_id: str, updated_reservation: PydanticReservation, db: Session = Depends(get_db)):
    """
    Edit a reservation
    """
    reservation = db.query(SQLAlchemyReservation).filter(SQLAlchemyReservation.id == reservation_id).first()
    if not reservation:
        raise HTTPException(status_code=404, detail="Reservation not found")

    reservation.tripId = updated_reservation.trip.id if updated_reservation.trip else None
    reservation.date = updated_reservation.date or reservation.date
    reservation.reservedSeats = updated_reservation.reservedSeats
    reservation.totalPrice = updated_reservation.totalPrice
    reservation.userId = updated_reservation.userId

    db.commit()
    db.refresh(reservation)
    return reservation


@router.delete(
    '/v1/reservations/{reservation_id}',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
    },
    tags=['Reservations'],
)
def delete_reservation(reservation_id: str, db: Session = Depends(get_db)):
    """
    Delete a reservation
    """
    reservation = db.query(SQLAlchemyReservation).filter(SQLAlchemyReservation.id == reservation_id).first()
    if not reservation:
        raise HTTPException(status_code=404, detail="Reservation not found")

    db.delete(reservation)
    db.commit()
    return {"message": "Reservation deleted successfully"}
