"""Initial migration

Revision ID: 1829d1d2fb2a
Revises: 
Create Date: 2025-02-07 09:25:20.128252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1829d1d2fb2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('boatLicense', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('individual', 'professional', name='status'), nullable=True),
    sa.Column('companyName', sa.String(), nullable=True),
    sa.Column('activityType', sa.String(), nullable=True),
    sa.Column('siretNumber', sa.String(), nullable=True),
    sa.Column('rcNumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_table('boats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('manufactureYear', sa.String(), nullable=True),
    sa.Column('photoUrl', sa.String(), nullable=True),
    sa.Column('licenseType', sa.Enum('coastal', 'river', name='license_type_enum'), nullable=True),
    sa.Column('boatType', sa.Enum('open', 'cabin', 'catamaran', 'sailboat', 'jet_ski', 'canoe', name='boat_type_enum'), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('depositAmount', sa.Float(), nullable=True),
    sa.Column('maxCapacity', sa.Integer(), nullable=True),
    sa.Column('numberOfBeds', sa.Integer(), nullable=True),
    sa.Column('homePort', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('engineType', sa.Enum('diesel', 'gasoline', 'none', name='engine_type_enum'), nullable=True),
    sa.Column('enginePower', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boats_id'), 'boats', ['id'], unique=False)
    op.create_index(op.f('ix_boats_name'), 'boats', ['name'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('practicalInfo', sa.String(), nullable=True),
    sa.Column('tripType', sa.String(), nullable=True),
    sa.Column('rateType', sa.String(), nullable=True),
    sa.Column('startDates', sa.String(), nullable=True),
    sa.Column('endDates', sa.String(), nullable=True),
    sa.Column('departureTimes', sa.String(), nullable=True),
    sa.Column('endTimes', sa.String(), nullable=True),
    sa.Column('passengerCount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('boat_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_title'), 'trips', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_title'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_boats_name'), table_name='boats')
    op.drop_index(op.f('ix_boats_id'), table_name='boats')
    op.drop_table('boats')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
