"""add reservations table

Revision ID: 6d21b8703408
Revises: 1829d1d2fb2a
Create Date: 2025-02-07 15:06:28.471434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d21b8703408'
down_revision: Union[str, None] = '1829d1d2fb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tripId', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reservedSeats', sa.Integer(), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tripId'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
