"""Add login and hashedPassword fields to users table

Revision ID: 80c1a07ba518
Revises: e9f76cf7cd28
Create Date: 2025-02-22 16:59:44.819309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c1a07ba518'
down_revision: Union[str, None] = 'e9f76cf7cd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashedPassword', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'hashedPassword')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
