"""Correction des relations Trip, Reservation et Boat

Revision ID: ab8d05811e3c
Revises: ab91875035e5
Create Date: 2025-02-22 17:05:47.371629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8d05811e3c'
down_revision: Union[str, None] = 'ab91875035e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
