"""Modification du modèle SQLAlchemy

Revision ID: d4b527b727cd
Revises: 1829d1d2fb2a
Create Date: 2025-02-17 11:51:06.789730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b527b727cd'
down_revision: Union[str, None] = '1829d1d2fb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('dateOfCatch', sa.Date(), nullable=True))
    op.drop_column('pages', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('pages', 'dateOfCatch')
    # ### end Alembic commands ###
