"""Update user table

Revision ID: eed79015a52b
Revises: 
Create Date: 2025-01-17 16:06:47.566447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed79015a52b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_firstName', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_lastName', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('lastName', sa.VARCHAR(), nullable=True),
    sa.Column('firstName', sa.VARCHAR(), nullable=True),
    sa.Column('birthDate', sa.DATE(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('boatLicense', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), nullable=True),
    sa.Column('companyName', sa.VARCHAR(), nullable=True),
    sa.Column('activityType', sa.VARCHAR(), nullable=True),
    sa.Column('siretNumber', sa.VARCHAR(), nullable=True),
    sa.Column('rcNumber', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_lastName', 'users', ['lastName'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_firstName', 'users', ['firstName'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
