"""Trips

Revision ID: f15a3f4b9340
Revises: 
Create Date: 2025-01-17 16:08:10.584558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15a3f4b9340'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('practicalInfo', sa.String(), nullable=True),
    sa.Column('tripType', sa.String(), nullable=True),
    sa.Column('rateType', sa.String(), nullable=True),
    sa.Column('startDates', sa.String(), nullable=True),
    sa.Column('endDates', sa.String(), nullable=True),
    sa.Column('departureTimes', sa.String(), nullable=True),
    sa.Column('endTimes', sa.String(), nullable=True),
    sa.Column('passengerCount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_title'), 'trips', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_title'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
