# generated by fastapi-codegen:
#   filename:  FF_API.yaml
#   timestamp: 2024-11-22T13:36:24+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional, Union

from fastapi import Path, Query

from .models import Boat, Error, Log, Page, Reservation, Status, Trip, User
