# generated by fastapi-codegen:
#   filename:  FF_API.yaml
#   timestamp: 2024-11-22T13:36:24+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional, Union

from fastapi import Path, Query

from .models import Boat, Error, Log, Page, Reservation, Status, Trip, UserRead

from sqlalchemy.orm import Session
from app.db import SessionLocal

def get_db():
    """
    Dependency that provides a database session.
    Automatically closes the session after use.
    """
    db: Session = SessionLocal()
    try:
        yield db
    finally:
        db.close()
