# generated by fastapi-codegen:
#   filename:  FF_API.yaml
#   timestamp: 2024-11-22T13:36:24+00:00

from __future__ import annotations

from fastapi import FastAPI
from pathlib import Path
import yaml

from .routers import boats, log, reservations, trips, users
from .database import Base, engine  # Importer la base et l'engin SQLAlchemy
from .models_sqlalchemy import User, Boat, Trip, Reservation, Log, Page  # Importer les modèles SQLAlchemy

# Initialisation de l'application FastAPI
app = FastAPI(
    title='Fisher Fans API',
    description='API for managing users, boats, trips, reservations, and logs.',
    version='1.0.0',
    servers=[
        {
            'url': 'https://api.fisherfans.local/api',
            'description': 'Secure local development server',
        }
    ],
)

# Inclusion des routers
app.include_router(boats.router)
app.include_router(log.router)
app.include_router(reservations.router)
app.include_router(trips.router)
app.include_router(users.router)


# Endpoint racine pour vérifier que l'application fonctionne
@app.get("/")
async def root():
    return {"message": "Gateway of the App"}


# Charger FF_API.yaml et configurer l'OpenAPI personnalisé
def custom_openapi():
    openapi_path = Path(__file__).parent.parent / "FF_API.yaml"  # Chemin vers le fichier FF_API.yaml
    if openapi_path.is_file():
        with open(openapi_path, "r") as file:
            openapi_spec = yaml.safe_load(file)
        return openapi_spec
    else:
        print(f"FF_API.yaml not found at {openapi_path}")
        return app.openapi_schema  # Par défaut, utilise le schéma généré automatiquement

# Associer le schéma OpenAPI personnalisé à l'application
app.openapi = custom_openapi
# Initialisation de la base de données
@app.on_event("startup")
async def startup_event():
    """
    Lors du démarrage de l'application, crée les tables nécessaires
    dans la base de données en utilisant les modèles SQLAlchemy.
    """
    print("Initializing database...")
    Base.metadata.create_all(bind=engine)
    print("Database initialized!")